name: "[Feature] Terraform Validate Feature Branch Pipeline"
run-name: User ${{ github.actor }} is validating terraform on branch ${{ github.ref }}
on:
  push:
    branches:    
      - 'feature/**'
jobs:
  call-workflow-passing-data:
    uses: paulosobral/amp-02-infra-reusable/.github/workflows/simple-infra-01-validate-terraform.yml@v1.0.0
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}